#!/bin/sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
/usr/bin/osascript <<-EOF

    tell application "System Events"
        activate
        display dialog "Hello world ${DIR}"
    end tell

EOF
"${DIR}/bin/node" "${DIR}/../hft/server/server.js"


